version: '3.1'

services:
  # Veritabanı Servisi
  db:
    image: mysql:8.0
    container_name: woo_mng_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  # WordPress Servisi
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: woo_mng_app
    restart: always
    ports:
      - "8000:80" # Tarayıcıdan localhost:8000 ile erişeceğiz
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      # WordPress dosyalarını kalıcı yapıyoruz
      - wp_data:/var/www/html
      # KRİTİK NOKTA: Kendi eklenti klasörümüzü içeriye "mount" ediyoruz.
      # Böylece Linux'ta yazdığın kod anında container içinde çalışacak.
      - ./wp-content/plugins/wc-mng-kargo:/var/www/html/wp-content/plugins/wc-mng-kargo

  # Veritabanı Yönetimi (Opsiyonel ama debug için şart)
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: woo_mng_pma
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword

volumes:
  db_data:
  wp_data:
